version: "3"
services:
  mongodb:
    image: mongo:3.4
  scrapy:
    build: .
    depends_on:
      - mongodb
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    command: start-notebook.sh
